### PR TITLE
🔧(CI) Add test and publish actions

### PR DESCRIPTION
**Pull request by Nakasar**
- Add github action on push to run tests & build.
- Add github action on release to test&build then publish the packages.
- Configure lerna to run tests and publish tasks on all packages.
- Add build config to individual packages.

I have published the packages as 1.0.0. As the repo had no specific build configuration for each packages I added one very basic.
@ValeriyDP @VladyslavKhymenkoDevPro it would be great if you could verify that the builded and published packages (`@erc-3643/core`, `@erc-3643/react-useDapp`, `@erc-3643/vue-useDapp`) work correctly with the demo apps and the uniswap integration.

On a further note, it may be useful to add a `README.md` in each package folder including some basic documentation for the package it refers to.

### CODE REVIEW

**Comment by VladyslavKhymenkoDevPro** [comment]
We've checked with @ValeriyDP and found out that the packages build configuration files need some adjusting.

After the fixes both demo applications and Uniswap integration work correctly while using the packages. I've created [a PR](https://github.com/ERC-3643/erc3643-packages/pull/2) for those fixes, that PR needs to be merged in the `feature/publish` branch before merging to `master`.

Would you be able to re-build and re-publish the packages after merging https://github.com/ERC-3643/erc3643-packages/pull/2 into the `feature/publish` branch?

Thank you!

**Comment by VladyslavKhymenkoDevPro** [comment]
@Nakasar 
Hey Kevin, just want to let you know that there will be another fix for the `react-useDapp` package sometime next week

**Comment by Nakasar** [comment]
> @Nakasar Hey Kevin, just want to let you know that there will be another fix for the `react-useDapp` package coming sometime next week

I published version 1.0.2 of the packages with the current code base :)

**Comment by VladyslavKhymenkoDevPro** [comment]
@Nakasar 
PR with fixes to the `react-usedapp` package along with demo application fixes is ready here - #3 

Please note the new versions of the `core`, `react-usedapp` and `vue-usedapp` packages, would you mind updating those in the NPM registry after merging #3 into #1?

Thank you

**Comment by Nakasar** [comment]
Merged and deployed!
To deploy new version from now on, we can merge to master via a PR and create a release, targeting a new tag that.

**Pull request merged**
